### PR TITLE
Add static buttons to each message

### PR DESCRIPTION
**Pull request by Appelg**
Hello. 

This PR adds the ability to add static buttons to each message. 

serilog_buttons

### CODE REVIEW

**Comment by Appelg** [comment]
@SeppPenner Hello! Did you have a chance to look at this yet?

**Comment by SeppPenner** [comment]
I wanted to fix the other issue as well with one release, but I guess, I will just add this already before.

**Comment by SeppPenner** [comment]
This is added in the next version, 1.1.0. Can you check this for me, please? :)

**Comment by Appelg** [comment]
Works fine, thanks!

**Pull request merged**
