### PR TITLE
Fix to allow use of Teams Incoming Webhook using PowerAutomateWorkflow

### PR DESCRIPTION
**Pull request by veraw**
As per Issue #33, needed support to use the newer Teams Incoming WebHook that uses the PowerAutomate Workflow approach. This PR add's additional option "UsePowerAutomateWorkflow" (default to false to not break existing usage). When option set to true, then will format using AdaptiveCards to serialize to required JSON format for the PowerAutomate Workflow.

### CODE REVIEW

**Comment by fernandodilland** [comment]
Thank you for your implementation of Power Apps. Unfortunately, Microsoft will stop allowing Office 365 connectors in Teams with its Incoming Webhook, and with this proposal, it will work well with Microsoft's new recommendation.

**Comment by maleet** [comment]
Can it be merged?

**Comment by mmauri** [comment]
Please, if this works, can we have it merged ?

**Comment by gdmarconetto** [comment]
Hello, any updates on this? It would be very useful. Thanks!

**Comment by SeppPenner** [comment]
@all-contributors please add @veraw for code, doc, test

**Pull request merged**
